routes/web.php
<?php

use App\Http\Controllers\Admin\OpenTestController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\LessonController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NomzodController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/{phone}', [HomeController::class, 'authPhoneNumber'])->where('phone', '[0-9]+');

    Route::get('test/{lesson_id}/{rekrut_id}', [TestController::class, 'testSolving'])->name('begin.test');
    Route::post('end/{lesson_id}', [TestController::class, 'endTest'])->name('end.test');
    Route::get('result/{lesson_id}/{rekrut_id}', [TestController::class, 'resultTest'])->name('result.test');

Route::middleware('auth')->group(function () {

    // Route::get('/', function () {
    //     return view('index');
    // });
    
    Route::get('/', [HomeController::class, 'index']);

    
    Route::group(['prefix'=>'admin'], function(){
    
        Route::get('/', function () {
            return view('admin.layouts.app');
        })->name('admin');
    
        Route::get('nomzodlar', [NomzodController::class, 'viewNomzodlar'])->name('nomzodlar');

        Route::resource('teacher', TeacherController::class);
        Route::resource('course', CourseController::class);
        Route::resource('lesson', LessonController::class);
        Route::resource('open-test', OpenTestController::class);
    });
    
    Route::get('lessons/{id?}', [LessonController::class, 'viewLessons'])->name('lessons');

    Route::get('answers', [TestController::class, 'answers'])->name('answers');

    // Route::get('logout', [TestController::class, 'logout'])->name('logout');
    // Route::get('view-lesson/{id}', [LessonController::class, 'viewLessons'])->name('view-lesson');

    // Route::get('test/{lesson_id}/{rekrut_id}', [TestController::class, 'testSolving'])->name('begin.test');
    // Route::post('end/{lesson_id}', [TestController::class, 'endTest'])->name('end.test');
    // Route::get('result/{lesson_id}/{rekrut_id}', [TestController::class, 'resultTest'])->name('result.test');

    #nomzod-begin
    Route::get('nomzod-list', [NomzodController::class, 'list'])->name('nomzod.list');
    Route::get('nomzod-reg', [NomzodController::class, 'reg'])->name('nomzod.reg');
    Route::post('nomzod-update/{id}', [NomzodController::class, 'update'])->name('nomzod.update');
    
    Route::post('nomzod-regis/{id}', [NomzodController::class, 'regis'])->name('nomzod.regis');

    Route::post('nomzod-ball/{id}', [NomzodController::class, 'ball'])->name('nomzod.ball');


    // Route::get('reyting', [NomzodController::class, 'ball'])->name('reyting');
    #nomzod-end


});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/NomzodController.php
<?php

namespace App\Http\Controllers;

use App\Models\AcademyCategoryBall;
use App\Models\AcademyStudentBall;
use App\Models\AcademyUser;
use App\Models\Rekrut;
use App\Models\RekrutGroup;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Http;

class NomzodController extends Controller
{
    public function list()
    {
        $groups = RekrutGroup::orderBy('id','DESC')->first();

        $rekruts = Rekrut::with('user')->where('group_id',2)->where('xolat',3)->get();

        // dd($rekruts);

        return view('pages.nomzod.list',[
            'rekruts' => $rekruts
        ]);
        
    }

    public function reg()
    {
        $groups = RekrutGroup::orderBy('id','ASC')->first();

        $rekruts = Rekrut::with('user')->where('xolat',3)->get();
        // $rekruts = Rekrut::with('user')->whereIn('xolat',[1,2,3,4,5,6,7])->get();

        $ustoz = DB::table('tg_user')->orderBy('first_name','ASC')->get();
        $pharmacy = DB::table('tg_pharmacy')->orderBy('name','ASC')->get();

        // dd($rekruts);

        return view('pages.nomzod.reg',[
            'rekruts' => $rekruts,
            'ustoz' => $ustoz,
            'pharmacy' => $pharmacy,
        ]);
        
    }

    public function regis(Request $request,$id)
    {

        $rekruts = Rekrut::find($id);

        $academy = AcademyUser::where('rekrut_id',$id)->first();
        
        $new = DB::table('tg_user')->insertGetId([
            'password' => Hash::make($academy->parol),
            'last_login' => NULL,
            'is_superuser' => FALSE,
            'username' => $academy->username,
            'first_name' => $rekruts->full_name,
            'last_name' => $rekruts->last_name,
            'phone_number' => $rekruts->phone,
            'is_staff' => FALSE,
            'is_active' => TRUE,
            'is_verified' => TRUE,
            'date_joined' => date('Y-m-d'),
            'district_id' => $rekruts->district_id,
            'region_id' => $rekruts->region_id,
            'specialty_id' => 1,
            'email' => NULL,
            'tg_id' => 990821015,
            'birthday' => $academy->birthday,
            'admin' => FALSE,
            'write_time' => date('Y-m-d'),
            'salary' => 1500000,
            'pr' => $academy->parol,
            'tg_file_id' => NULL,
            'rol_id' => 27,
            'last_seen' => NULL,
            'teacher' => FALSE,
            'image_change' => TRUE,
            'pharmacy_id' => NULL,
            'image_url' => 'https://telegra.ph//file/04f99aa16eebd4af2a42c.jpg',
            'status' => 0,
            'level' => 0,
            'rm' => 0,
            'first_enter' => 0,

        ]);        

        DB::table('daily_works')->insertGetId([
            'user_id' => $new,
            'start_work' => '09:00:00',
            'finish_work' => '18:00:00',
            'start' => '2023-03-15'
        ]);

        DB::table('tg_pharmacy_users')->insertGetId([
            'user_id' => $new,
            'pharma_id' => $request->apteka,
        ]);

        DB::table('teacher_users')->insertGetId([
                'teacher_id' => $request->ustoz,
                'user_id' => $new,
                'week_date' => '2023-10-09',
            ]);

        $response = Http::post('notify.eskiz.uz/api/auth/login', [
            'email' => 'mubashirov2002@gmail.com',
            'password' => 'PM4g0AWXQxRg0cQ2h4Rmn7Ysoi7IuzyMyJ76GuJa'
        ]);
        $token = $response['data']['token'];

        $sms = Http::withToken($token)->post('notify.eskiz.uz/api/message/sms/send', [
            'mobile_phone' => substr($rekruts->phone,1),
            'message' => 'Login   ' . $academy->username  . '   Parol   '. $academy->parol .' .  Saytga kirish uchun link ustiga bosing  jang.novatio.uz/login',
            'from' => '4546',
            'callback_url' => 'http://0000.uz/test.php'
        ]);

        return redirect()->back();
        
    }
    public function update(Request $request,$id)
    {
        $nomzod = Rekrut::find($id);

        $username = 'nvt'.rand(100,999);
        $parol = rand(1000,9999);

        $user = new AcademyUser();
        $user->birthday = $request->birthday;
        $user->rekrut_id = $request->id;
        $user->parol = $parol;
        $user->username = $username;
        $user->password = Hash::make($parol);
        $user->save();


        $response = Http::post('notify.eskiz.uz/api/auth/login', [
            'email' => 'mubashirov2002@gmail.com',
            'password' => 'PM4g0AWXQxRg0cQ2h4Rmn7Ysoi7IuzyMyJ76GuJa'
        ]);
        $token = $response['data']['token'];

        $sms = Http::withToken($token)->post('notify.eskiz.uz/api/message/sms/send', [
            'mobile_phone' => substr($nomzod->phone,1),
            'message' => 'Login   ' . $username  . '   Parol   '. $parol .' .  Saytga kirish uchun link ustiga bosing  academy.novatio.uz',
            'from' => '4546',
            'callback_url' => 'http://0000.uz/test.php'
        ]);

        return redirect()->back();

    }

    public function viewNomzodlar()
    {
        $users = AcademyUser::with('rekrut')->where('status',1)->get();

        $category = AcademyCategoryBall::all();

        return view('admin.pages.nomzod.list',[
            'users' => $users,
            'category' => $category,
        ]);
    }

    public function ball(Request $request, $id)
    {
        $new = new AcademyStudentBall;
        $new->user_id = $id;
        $new->category = $request->xolat;
        $new->ball = $request->ball;
        $new->save();

        return redirect()->back();

    }
}

resources/views/pages/nomzod/list.blade.php
@extends('admin.layouts.app')
@section('admin-content')
    <div class="dashboard__content bg-light-4 pt-1">

        <div class="row y-gap-30">
            <div class="col-12">
                <div class="rounded-16 bg-white shadow-4 h-100">
                    {{-- <div class="d-flex items-center py-20 px-30 border-bottom-light">
              <h2 class="text-17 lh-1 fw-500">Page Head</h2>
            </div> --}}
                    <div class="d-flex justify-between items-center py-20 px-30 border-bottom-light">
                        <h2 class="text-17 lh-1 fw-500">Nomzodlar ro'yhati</h2>
                        {{-- <div>
                            <a href="{{ route('course.create') }}" class="button h-50 px-30 -purple-1 text-white">Yangi
                                test qo'shish</a>
                        </div> --}}
                    </div>
                    <div class="py-30 px-30">
                        <div class="col-lg-12">
                            <table class="table w-1/1">
                                <thead>
                                    <tr>
                                        <th>FIO</th>
                                        <th>Izoh</th>
                                        <th>Yosh</th>
                                        <th>Viloyat</th>
                                        <th>Tuman</th>
                                        <th>Guruh</th>
                                        <th>Birth</th>
                                        <th>Saqlash</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  @isset($rekruts)
                                      @foreach ($rekruts as $item)
                                      <form action="{{route('nomzod.update',$item->id)}}" method="post">
                                        @csrf
                                        <tr>
                                            <td>{{$item->full_name}} {{$item->last_name}}</td>
                                            <td>{{$item->phone}}</td>
                                            <td>{{$item->age}}</td>
                                            <td>{{$item->region->name}}</td>
                                            <td>{{$item->district->name}}</td>
                                            <td>{{$item->group->title}}</td>
                                            <td>
                                                @if($item->user == null)
                                                <input type="date" name="birthday">

                                                @else
                                                {{$item->user->birthday}}
                                                
                                                @endif
                                                
                                            </td>
                                            <td> 
                                                @if($item->user == null)

                                                <button type="submit" class="btn btn-primary -purple-1">
                                                    <i class="fas fa-save" ></i>
                                                </button>
                                                
                                                @else
                                                
                                                
                                                @endif
                                                
                                            </td>
                                            
                                        </tr>
                                      </form>
                                      @endforeach
                                  @endisset

                                </tbody>
                            </table>
                        </div>                                   

                        {{-- @include('components.paginate',['pagination_v' => $courses]) --}}

                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection
@section('admin-script')
@endsection

resources/views/pages/nomzod/reg.blade.php
@extends('admin.layouts.app')
@section('admin-content')
    <div class="dashboard__content bg-light-4 pt-1">

        <div class="row y-gap-30">
            <div class="col-12">
                <div class="rounded-16 bg-white shadow-4 h-100">
                    {{-- <div class="d-flex items-center py-20 px-30 border-bottom-light">
              <h2 class="text-17 lh-1 fw-500">Page Head</h2>
            </div> --}}
                    <div class="d-flex justify-between items-center py-20 px-30 border-bottom-light">
                        <h2 class="text-17 lh-1 fw-500">Nomzodlar ro'yhati</h2>
                        {{-- <div>
                            <a href="{{ route('course.create') }}" class="button h-50 px-30 -purple-1 text-white">Yangi
                                test qo'shish</a>
                        </div> --}}
                    </div>
                    <div class="py-30 px-30">
                        <div class="col-lg-12">
                            <table class="table w-1/1">
                                <thead>
                                    <tr>
                                        <th>FIO</th>
                                        <th>Izoh</th>
                                        <th>Viloyat</th>
                                        <th>Guruh</th>
                                        <th>Birth</th>
                                        <th>Ustoz</th>
                                        <th>Apteka</th>
                                        <th>Saqlash</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  @isset($rekruts)
                                      @foreach ($rekruts as $item)
                                      <form action="{{route('nomzod.regis',$item->id)}}" method="post">
                                        @csrf
                                        <tr>
                                            <td>{{$item->full_name}} {{$item->last_name}}</td>
                                            <td>{{$item->phone}}</td>
                                            <td>{{$item->region->name}}</td>
                                            <td>{{$item->group->title}}</td>
                                            <td>
                                                @if($item->user == null)
                                                <input type="date" name="birthday">

                                                @else
                                                {{$item->user->birthday}}
                                                
                                                @endif
                                                
                                            </td>
                                            <td> 
                                                <select name="ustoz">
                                                    @foreach ($ustoz as $ust)
                                                        <option value="{{$ust->id}}">{{$ust->first_name}} {{$ust->last_name}}</option>
                                                    @endforeach
                                                </select>
                                                
                                            </td>
                                            <td> 
                                                <select name="apteka">
                                                    @foreach ($pharmacy as $ust)
                                                        <option value="{{$ust->id}}">{{$ust->name}}</option>
                                                    @endforeach
                                                </select>
                                                
                                            </td>
                                            <td>
                                                <button class="btn btn-primary" type="submit">
                                                    saqlash
                                                </button>
                                            </td>
                                        </tr>
                                      </form>
                                      @endforeach
                                  @endisset

                                </tbody>
                            </table>
                        </div>                                   

                        {{-- @include('components.paginate',['pagination_v' => $courses]) --}}

                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection
@section('admin-script')
@endsection