routes/web.php
<?php

use App\Http\Controllers\Admin\OpenTestController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\LessonController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NomzodController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/{phone}', [HomeController::class, 'authPhoneNumber'])->where('phone', '[0-9]+');

    Route::get('test/{lesson_id}/{rekrut_id}', [TestController::class, 'testSolving'])->name('begin.test');
    Route::post('end/{lesson_id}', [TestController::class, 'endTest'])->name('end.test');
    Route::get('result/{lesson_id}/{rekrut_id}', [TestController::class, 'resultTest'])->name('result.test');

Route::middleware('auth')->group(function () {

    // Route::get('/', function () {
    //     return view('index');
    // });
    
    Route::get('/', [HomeController::class, 'index']);

    
    Route::group(['prefix'=>'admin'], function(){
    
        Route::get('/', function () {
            return view('admin.layouts.app');
        })->name('admin');
    
        Route::get('nomzodlar', [NomzodController::class, 'viewNomzodlar'])->name('nomzodlar');

        Route::resource('teacher', TeacherController::class);
        Route::resource('course', CourseController::class);
        Route::resource('lesson', LessonController::class);
        Route::resource('open-test', OpenTestController::class);
    });
    
    Route::get('lessons/{id?}', [LessonController::class, 'viewLessons'])->name('lessons');

    Route::get('answers', [TestController::class, 'answers'])->name('answers');

    // Route::get('logout', [TestController::class, 'logout'])->name('logout');
    // Route::get('view-lesson/{id}', [LessonController::class, 'viewLessons'])->name('view-lesson');

    // Route::get('test/{lesson_id}/{rekrut_id}', [TestController::class, 'testSolving'])->name('begin.test');
    // Route::post('end/{lesson_id}', [TestController::class, 'endTest'])->name('end.test');
    // Route::get('result/{lesson_id}/{rekrut_id}', [TestController::class, 'resultTest'])->name('result.test');

    #nomzod-begin
    Route::get('nomzod-list', [NomzodController::class, 'list'])->name('nomzod.list');
    Route::get('nomzod-reg', [NomzodController::class, 'reg'])->name('nomzod.reg');
    Route::post('nomzod-update/{id}', [NomzodController::class, 'update'])->name('nomzod.update');
    
    Route::post('nomzod-regis/{id}', [NomzodController::class, 'regis'])->name('nomzod.regis');

    Route::post('nomzod-ball/{id}', [NomzodController::class, 'ball'])->name('nomzod.ball');


    // Route::get('reyting', [NomzodController::class, 'ball'])->name('reyting');
    #nomzod-end


});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/Lesson.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Lesson extends Model
{
    use HasFactory;

    protected $table = 'academy_lessons';

    protected $guarded = [];

    public function course()
    {
        return $this->belongsTo(Course::class,'course_id','id');
    }
}

app/Http/Controllers/LessonController.php
<?php

namespace App\Http\Controllers;

use App\Models\Course;
use App\Models\Lesson;
use App\Models\LessonUserCheck;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LessonController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $lessons = Lesson::with('course')->orderBy('id')->paginate(5);

        return view('admin.pages.lesson.list',[
            'lessons' => $lessons,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        $courses = Course::orderBy('id','ASC')->get();

        return view('admin.pages.lesson.create',[
            'courses' => $courses,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs = $request->all();

        // unset($inputs['_token']);

        $new_quiz = new Lesson($inputs);

        $new_quiz->save();
        
        return redirect()->back()->with('save_success','Ma\'lumotlar saqlandi.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function lessons()
    {
        $course = Course::with(['lesson' => function($q){
            $q->orderBy('sort','ASC');
        }])->orderBy('id','ASC')->limit(1)->get();

        $lesson = Lesson::where('course_id',$course[0]->id)->orderBy('sort','ASC')->first();

        
        $ids = Lesson::where('check_test',0)->orderBy('sort','ASC')->first();

        return view('pages.lessons',[
            'course' => $course,
            'lesson' => $lesson,
            'ids' => $ids,
        ]);
    }

    public function viewLessons($id = null)
    {
        $course = Course::with(['lesson' => function($q){
            $q->orderBy('sort','ASC');
        }])->orderBy('id','ASC')->limit(1)->get();

        if($id)
        {
            $lesson = Lesson::find($id);
        }else{
            $lesson = Lesson::where('course_id',$course[0]->id)->orderBy('sort','ASC')->first();
        }

        $checks = LessonUserCheck::where('user_id',Auth::id())->pluck('lesson_id')->toArray();

        // return $checks;

        // $ids = Lesson::where('check_test',0)->orderBy('sort','ASC')->first();
        $ids = Lesson::whereNotIn('id',$checks)->orderBy('sort','ASC')->first();

        return view('pages.lessons',[
            'course' => $course,
            'lesson' => $lesson,
            'ids' => $ids,
            'checks' => $checks,
        ]);
    }
}

resources/views/admin/pages/lesson/create.blade.php
@extends('admin.layouts.app')
@section('admin-content')
    <div class="dashboard__content bg-light-4 pt-1">

        <div class="row x-gap-60 y-gap-30 mt-10">
            @if ($message = Session::get('save_success'))
              <div class="col-12 alerts-all" style="padding-top: 5px;padding-bottom: 0px;">
                <div class="d-flex items-center justify-between bg-success-1 pl-30 pr-20 py-10 rounded-8">
                    <div class="text-success-2 lh-1 fw-500">{{ $message }}</div>
                </div>
              </div>
            @endif
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="col-12 alerts-all" style="padding-top: 5px;padding-bottom: 0px;">
                        <div class="d-flex items-center justify-between bg-error-1 pl-30 pr-20 py-10 rounded-8">
                            <div class="text-error-2 lh-1 fw-500">{{ $error }}</div>
                            {{-- <div class="text-error-2 size-20" data-feather="x"></div> --}}
                        </div>
                    </div>
                @endforeach
            @endif
            <div class="d-flex justify-between items-center py-20 px-30 border-bottom-light">
                <h2 class="text-17 lh-1 fw-500">Dars qo'shish</h2>
                  <div>
                    <a href="{{route('lesson.index')}}" class="button h-50 px-30 -purple-1 text-white">Darslar ro'yhati</a>
                  </div>
              </div>
            <form action="{{ route('lesson.store') }}" method="POST" class="contact-form">
                @csrf
                <div class="row">
                    <div class="col-lg-12 mb-2">
                      <div class="col-12">
                          <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Dars nomi</label>
                          <input type="text" name="title" placeholder="Dars nomini kiriting...">
                      </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="col-12">
                            <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Dars izoh</label>
                            <textarea placeholder="Izohni kiriting..." rows="3" name="description"></textarea>
                        </div>
                    </div>
                    <div class="col-lg-12">
                      <div class="col-12">
                          <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Video linki</label>
                          <input type="text" name="video_link" placeholder="Video linkini kiriting...">
                      </div>
                    </div>
                    <div class="col-lg-12">
                      <div class="col-12">
                          <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Tartib raqami</label>
                          <input type="text" name="sort" placeholder="Tartib raqamini kiriting...">
                      </div>
                    </div>
                    <div class="col-lg-12">
                      <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Kursni tanlang</label>
                        <div class="form-select">
                            <select class="selectize wide js-selectize" name="course_id">
                                <option selected disabled></option>
                                @foreach ($courses as $item)
                                  <option value="{{$item->id}}" style="padding: 0px 24px;">{{$item->title}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-12">
                        <div class="form-select mt-35">
                          <button type="submit" class="button -icon -outline-purple-1 text-purple-1"
                              style="width: 100%;">
                              Saqlash
                          </button>
                        </div>
                    </div>
              </div>

            </form>
        </div>

    </div>
@endsection
@section('admin-script')
<script>
  $(document).ready(function() {
    $(".alerts-all").fadeTo(2000, 500).slideUp(2000, function() {
      $(".alerts-all").slideUp(2000);
    });
  });
</script>
@endsection

resources/views/admin/pages/lesson/list.blade.php
@extends('admin.layouts.app')
@section('admin-content')
    <div class="dashboard__content bg-light-4 pt-1">

        <div class="row y-gap-30">
            <div class="col-12">
                <div class="rounded-16 bg-white shadow-4 h-100">
                    {{-- <div class="d-flex items-center py-20 px-30 border-bottom-light">
              <h2 class="text-17 lh-1 fw-500">Page Head</h2>
            </div> --}}
                    <div class="d-flex justify-between items-center py-20 px-30 border-bottom-light">
                        <h2 class="text-17 lh-1 fw-500">Testlar ro'yhati</h2>
                        <div>
                            <a href="{{ route('lesson.create') }}" class="button h-50 px-30 -purple-1 text-white">Yangi
                                test qo'shish</a>
                        </div>
                    </div>
                    <div class="py-30 px-30">
                        <div class="col-lg-12">
                            <table class="table w-1/1">
                                <thead>
                                    <tr>
                                        <th>Nomi</th>
                                        <th>Kurs</th>
                                        <th>Izoh</th>
                                        <th>Link</th>
                                        <th>Tartib raqami</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  @isset($lessons)
                                      @foreach ($lessons as $item)
                                      <tr>
                                        <td>{{$item->title}}</td>
                                        <td>{{$item->course->title}}</td>
                                        <td>{{$item->description}}</td>
                                        <td>{{$item->video_link}}</td>
                                        <td>{{$item->sort}}</td>
                                        
                                      </tr>
                                      @endforeach
                                  @endisset

                                </tbody>
                            </table>
                        </div>                                   

                        @include('components.paginate',['pagination_v' => $lessons])

                    </div>
                </div>
            </div>
        </div>

    </div>
@endsection
@section('admin-script')
@endsection