routes/web.php
<?php

use App\Http\Controllers\Admin\OpenTestController;
use App\Http\Controllers\CourseController;
use App\Http\Controllers\LessonController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\TestController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\NomzodController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Auth::routes();

Route::get('/{phone}', [HomeController::class, 'authPhoneNumber'])->where('phone', '[0-9]+');

    Route::get('test/{lesson_id}/{rekrut_id}', [TestController::class, 'testSolving'])->name('begin.test');
    Route::post('end/{lesson_id}', [TestController::class, 'endTest'])->name('end.test');
    Route::get('result/{lesson_id}/{rekrut_id}', [TestController::class, 'resultTest'])->name('result.test');

Route::middleware('auth')->group(function () {

    // Route::get('/', function () {
    //     return view('index');
    // });
    
    Route::get('/', [HomeController::class, 'index']);

    
    Route::group(['prefix'=>'admin'], function(){
    
        Route::get('/', function () {
            return view('admin.layouts.app');
        })->name('admin');
    
        Route::get('nomzodlar', [NomzodController::class, 'viewNomzodlar'])->name('nomzodlar');

        Route::resource('teacher', TeacherController::class);
        Route::resource('course', CourseController::class);
        Route::resource('lesson', LessonController::class);
        Route::resource('open-test', OpenTestController::class);
    });
    
    Route::get('lessons/{id?}', [LessonController::class, 'viewLessons'])->name('lessons');

    Route::get('answers', [TestController::class, 'answers'])->name('answers');

    // Route::get('logout', [TestController::class, 'logout'])->name('logout');
    // Route::get('view-lesson/{id}', [LessonController::class, 'viewLessons'])->name('view-lesson');

    // Route::get('test/{lesson_id}/{rekrut_id}', [TestController::class, 'testSolving'])->name('begin.test');
    // Route::post('end/{lesson_id}', [TestController::class, 'endTest'])->name('end.test');
    // Route::get('result/{lesson_id}/{rekrut_id}', [TestController::class, 'resultTest'])->name('result.test');

    #nomzod-begin
    Route::get('nomzod-list', [NomzodController::class, 'list'])->name('nomzod.list');
    Route::get('nomzod-reg', [NomzodController::class, 'reg'])->name('nomzod.reg');
    Route::post('nomzod-update/{id}', [NomzodController::class, 'update'])->name('nomzod.update');
    
    Route::post('nomzod-regis/{id}', [NomzodController::class, 'regis'])->name('nomzod.regis');

    Route::post('nomzod-ball/{id}', [NomzodController::class, 'ball'])->name('nomzod.ball');


    // Route::get('reyting', [NomzodController::class, 'ball'])->name('reyting');
    #nomzod-end


});

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Http/Controllers/TeacherController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.pages.teacher.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/pages/teacher/create.blade.php
@extends('admin.layouts.app')
@section('admin-content')
    <div class="dashboard__content bg-light-4 pt-1">

        <div class="row x-gap-60 y-gap-30 mt-10">
            @if ($message = Session::get('save_success'))
              <div class="col-12 alerts-all" style="padding-top: 5px;padding-bottom: 0px;">
                <div class="d-flex items-center justify-between bg-success-1 pl-30 pr-20 py-10 rounded-8">
                    <div class="text-success-2 lh-1 fw-500">{{ $message }}</div>
                    {{-- <div class="text-success-2 size-20" data-feather="x"></div> --}}
                </div>
              </div>
            @endif
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                    <div class="col-12 alerts-all" style="padding-top: 5px;padding-bottom: 0px;">
                        <div class="d-flex items-center justify-between bg-error-1 pl-30 pr-20 py-10 rounded-8">
                            <div class="text-error-2 lh-1 fw-500">{{ $error }}</div>
                            {{-- <div class="text-error-2 size-20" data-feather="x"></div> --}}
                        </div>
                    </div>
                @endforeach
            @endif
            <div class="d-flex justify-between items-center py-20 px-30 border-bottom-light">
                <h2 class="text-17 lh-1 fw-500">Ustoz qo'shish</h2>
                  <div>
                    <a href="{{route('open-test.index')}}" class="button h-50 px-30 -purple-1 text-white">Testlar ro'yhati</a>
                  </div>
              </div>
            <form action="{{ route('open-test.store') }}" method="POST" class="contact-form">
                @csrf
                <div class="row">
                    <div class="col-lg-12">
                        <div class="col-12">
                            <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Test savali</label>
                            <textarea placeholder="Savolni kiriting..." rows="3" name="question"></textarea>
                        </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="col-12">
                          <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Javob A</label>
                          <input type="text" name="name" placeholder="Javobni kiriting...">
                          {{-- <textarea placeholder="Javobni kiriting..." rows="2" name="answer_a"></textarea> --}}
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="col-12">
                          <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Javob B</label>
                          <textarea placeholder="Javobni kiriting..." rows="2" name="answer_b"></textarea>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="col-12">
                          <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Javob C</label>
                          <textarea placeholder="Javobni kiriting..." rows="2" name="answer_c"></textarea>
                      </div>
                    </div>
                    <div class="col-lg-6">
                      <div class="col-12">
                          <label class="text-16 lh-1 fw-500 text-dark-1 mb-10">Javob D</label>
                          <textarea placeholder="Javobni kiriting..." rows="2" name="answer_d"></textarea>
                      </div>
                    </div>
                    <div class="col-lg-6">
                        <label class="text-16 lh-1 fw-300 text-dark-1 mb-10">Test javobi</label>
                        <div class="form-select">
                            <select class="selectize wide js-selectize" name="answer">
                                <option selected disabled></option>
                                <option value="A" style="padding: 0px 24px;">A</option>
                                <option value="B" style="padding: 0px 24px;">B</option>
                                <option value="C" style="padding: 0px 24px;">C</option>
                                <option value="D" style="padding: 0px 24px;">D</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-select mt-35">
                          <button type="submit" class="button -icon -outline-purple-1 text-purple-1"
                              style="width: 100%;">
                              Saqlash
                          </button>
                        </div>
                    </div>
              </div>

            </form>
        </div>

    </div>
@endsection
@section('admin-script')
<script>
  $(document).ready(function() {
    $(".alerts-all").fadeTo(2000, 500).slideUp(2000, function() {
      $(".alerts-all").slideUp(2000);
    });
  });
</script>
@endsection